name: docker build

on:
  push:
    paths:
      - "Dockerfile"
      - "check_build.sh"
      - ".github/workflows/docker-image.yml"
      - ".version"
  schedule:
    - cron: '0 0 * * *'    
    
env:
  # Use x for Docker Hub if empty. ghcr.io / docker.io
  REGISTRY: docker.io    

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Check out the repo
      uses: actions/checkout@v2    
      # with:
        # token: ${{ secrets.GH_TOKEN }}      
    - 
      name: Setup QEMU
      uses: docker/setup-qemu-action@v1

    - 
      name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - 
      name: Login into registry ${{ env.REGISTRY }}   
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1      
      with:
        registry: ${{ env.REGISTRY }}   
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}   
    - 
      name: Build image and push to Docker Hub
      env:
        PUSH_USER: jetsung
        PUSH_EMAIL: skiy@jetsung.com   
      run: |
        bash check_build.sh
